sonar.projectKey=cyberhafid-ombrea
sonar.organization=cyberhafid-ombrea

sonar.sources=fastapi_api/src,react_app/src
sonar.tests=fastapi_api/tests,react_app/src/__tests__
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/alembic/**,react_app/src/__tests__/**

sonar.python.version=3.10
sonar.python.coverage.reportPaths=fastapi_api/coverage.xml

sonar.javascript.lcov.reportPaths=react_app/coverage/lcov.info

